name: kcli_plan 
on:
  workflow_dispatch:
    inputs:
      RUNNER:
        description: 'Github Action Runner Name'
        required: true
        default: 'ubuntu-latest'
      PLAN:
        description: 'Plan Name'
        required: true
        default: kcli_plan
      MOTD:
        description: 'motd'
        required: false
        default: Welcome to my home

jobs:
    requirements:
    runs-on:  ${{github.event.inputs.RUNNER}} 
    steps:
      - name: Install kcli
        run: |
          curl https://raw.githubusercontent.com/karmab/kcli/master/install.sh | bash
          # kcli create pool -p /var/lib/libvirt/images default
          # sudo setfacl -m u:$(id -un):rwx /var/lib/libvirt/images

      - uses: actions/checkout@v2
      - run: git pull origin ${GITHUB_REF##*/}

  deploy-plan:
    needs: requirements
    runs-on:  ${{github.event.inputs.RUNNER}} 
    steps:
      - name: Deploy kcli plan
        run: |
          kcli create plan --force -f kcli_plan.yml  -P motd=${{github.event.inputs.MOTD}}  ${{github.event.inputs.PLAN}} 
