#!/usr/bin/env bash

IF=ens3
BRIDGE=baremetal
for ip in $(ip -o addr |grep $IF | grep -v inet6 | awk '{print $4}') ; do 
  ip addr del $ip dev $IF
  #ip addr add $ip dev $BRIDGE
done
ip link set $IF master $BRIDGE
ip link set baremetal type bridge vlan_filtering 1
dhclient $BRIDGE
