parameters:
 image: centos8
 groups:
   firstnodes:
   - node1
   secondnodes:
   - node2

1_play:
 type: ansible
 verbose: true
 playbook: play1.yml
 groups: {{ groups }}

2_play:
 type: ansible
 playbook: play2.yml
 groups: {{ groups }}
 vms:
 - node1

node1:
 image: {{ image }}
 numcpus: 2
 memory: 3096

node2:
 image: {{ image }}
 numcpus: 2
 memory: 2048
