parameters:
 image: centos8stream
 network: default

myplay:
 type: ansible
 verbose: false
 playbook: prout.yml

testansible01:
 image: {{ image }} 
 memory: 1024
 numcpus: 1
 disks:
  - size: 10
 nets:
  - {{ network }}

testansible02:
 image: {{ image }} 
 memory: 1024
 numcpus: 1
 disks:
  - size: 10
 nets:
  - {{ network }}
